#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

runApplication blockMesh
restore0Dir
touch a.foam
runApplication setFields
decomposePar

mpirun -np 2 $(getApplication) -parallel > log 
#------------------------------------------------------------------------------
